app/Http/routes.php
<?php
use Illuminate\Support\Facades\DB;
Route::get('trial',function (){
});
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Support\Facades\Route;


Route::get('/','RouteController@index');
Route::get('home','RouteController@index');
Route::get('/password/email','Auth\PasswordController@getEmail');
Route::post('/password/email','Auth\PasswordController@postEmail');
Route::get('/password/reset/{token}','Auth\PasswordController@getReset');
Route::post('/password/reset','Auth\PasswordController@getReset');


Route::post('/user/login','HomeController@PostLogin');
Route::post('/user/register/{role}','HomeController@RegisterUsers')->middleware(['RegisterPermitter']);
Route::post('/contact','HomeController@Contact');


Route::group(['middleware' => 'auth'],function (){
    Route::get('/logout',array('as' => 'logout' ,'uses' => 'HomeController@LogOut'));
    Route::get('/dashboard',array('as' => 'dashboard' , 'uses' => 'RouteController@Dashboard') );

    Route::get('/overview',array('as' => 'overview' , 'uses' => 'PanelController@OverView' ))->middleware(['RoleChecker:overview']);
    Route::get('/clients', array('as' => 'clients', 'uses' => 'PanelController@Clients'))->middleware(['RoleChecker:clients']);
    Route::get('/employees', array('as' => 'employees', 'uses' => 'PanelController@employees'))->middleware(['RoleChecker:employees']);
    Route::get('/partners', array('as' => 'partners', 'uses' => 'PanelController@partners'))->middleware(['RoleChecker:partners']);
    Route::get('/cars', array('as' => 'cars', 'uses' => 'PanelController@cars'))->middleware(['RoleChecker:cars']);
    Route::get('/reservations', array('as' => 'reservations', 'uses' => 'PanelController@reservations'))->middleware(['RoleChecker:reservations']);
    Route::get('/recive', array('as' => 'recive', 'uses' => 'PanelController@recive'))->middleware(['RoleChecker:recive']);
    Route::get('/expenses',array('as' => 'expenses' , 'uses' => 'PanelController@expenses' ))->middleware(['RoleChecker:expenses']);
    Route::get('/reports', array('as' => 'reports', 'uses' => 'PanelController@reports'))->middleware(['RoleChecker:reports']);
    Route::get('/quickaccess', array('as' => 'quickaccess', 'uses' => 'PanelController@quick_access'))->middleware(['RoleChecker:quickaccess']);
    Route::get('/checkout',array('as'=>'checkout','uses'=>'ReservationController@ReservationCheckOut'));
    Route::post('/register/car',array('as' => 'register.car', 'uses' => 'CarsController@RegisterCar'))->middleware(['RoleChecker:cars']);
    Route::post('/client/delete','ClientsController@DeleteClient');
    Route::post('/partner/delete','PartnersController@DeletePartner');
    Route::post('/rent/car',array('as' => 'rent.car','uses' => 'ReservationController@CreateReservation'));
    Route::post('/calculate/reservation',array('as' => 'calculate.car.rent','uses' => 'ReservationController@CalculateReservation'));
    Route::post('/Reserve',array('as'=> '','uses' => 'ReservationController@FinalReservationStep'));
    Route::post('/reservation/delete',array('as'=> '','uses' => 'ReservationController@Delete'));
    Route::post('/renting/recive','ReservationController@Recive');
    Route::post('/employee/update','EmployeeController@Update');

    Route::get('user/{username}','ClientsController@Profile');
    Route::get('car/{carname}','CarsController@Profile');

    Route::post('/user/update','HomeController@UpdateUser');
    Route::post('/client/update','ClientsController@UpdateClient');
    Route::post('/client/dept/pay','ClientsController@PayDept');

    Route::post('/expenses/general/add','ExpensesController@AddGeneral');
    Route::post('/expenses/car/add','ExpensesController@AddCar');
    Route::post('/expenses/delete','ExpensesController@Delete');
    Route::post('/expenses/update','ExpensesController@Update');


    Route::post('/car/delete','CarsController@Delete');
    Route::post('/car/update','CarsController@Update');
    Route::post('/car/attachment','AttachmentsController@Car');
    Route::post('/client/attachment','AttachmentsController@Client');


});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['first_name','last_name', 'birthdate', 'address','password',
        'email','phone','national_id','role_id'];

    protected $dates = ['deleted_at'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo('App\models\Roles');
    }

    public function cars()
    {
        return $this->hasMany('App\models\Cars');
    }

    public function employee()
    {
        return $this->hasOne('App\models\Employees');
    }

    public function renting()
    {
        return $this->hasMany('App\models\Rentings');
    }
    public function attachments()
    {
        return $this->hasMany('App\models\Attachments');
    }
    public function getDisplayNameAttribute()
    {
        return $this->first_name . " " . $this->last_name;
    }

    public function getBirthAttribute()
    {
        $birthdate = explode(" ",$this->birthdate);
        return $birth = $birthdate[0];
    }

}

resources/views/pages/CarProfile.blade.php
    @extends('layouts.Profile')

@section('title')
    {{$car->type}}
@endsection
@section('desc')
    السيارة : {{$car->type}}
@endsection
@section('backto')
    {{URL::route('cars')}}
@endsection
@section('contents')
    @include('layouts.Expenses_Forms')
    <div id="AddAttachment-Popup" class="popup">
        <i class="fa fa-close text-danger" data-toggle="tooltip" data-placement="left" title="اغلاق"></i>
        <!--===== POPUP TITLE -=====-->
        <div class="popup-title">
            <h2>اضافة مرفق جديد</h2>
            <br>
            <hr>
            <hr>
        </div>
        <!--===== POPUP BODY ======-->
        <div class="popup-body text-center">
            <form id="CarAttach" type="POST">
                {!! csrf_field() !!}
                <input type="text" class="hidden" name="id" value="{{$car->id}}">
                <input type="text" class="hidden" name="plate_number" value="{{$car->plate_number}}">
                <div class="col-md-6 col-xs-12">
                    <input type="text" name="title" placeholder="عنوان المرفق">
                    <label id="general_expense_title"></label>
                </div>
                <div class=" col-md-6 col-xs-12 text-right">
                    <h5 style="float:right;margin:10px 20px;font-size:16px">اضافة صورة</h5>
                    <input type="file" name="picture" id="car_image">
                </div>
                <div class="clearfix"></div>
                <div class="text-center">
                    <button type="submit" class="main-btn">اضافة</button>
                </div>
                <div class="alert"role="alert">

                </div>
            </form>
        </div>
    </div>
    <div class="info box main-box">
        <h3 class="title">بيانات السيارة</h3>
        <form method="POST" id="Update">
            {!! csrf_field() !!}
            <input class="hidden" name="id" value="{{$car->id}}">
            <table border="1">

                <tr>
                    <th>
                        الاسم
                    </th>
                    <td>
                        <div class="col-xs-12">
                            <input type="text" name="type" value="{{$car->type}}">
                            <label class="alert" id="type"></label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        الموديل
                    </th>
                    <td>
                        <div class="col-xs-12">
                            <input type="text" name="model" value="{{$car->model }}">
                            <label class="alert" id="model"></label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        اللون
                    </th>
                    <td>
                        <div class="col-xs-12">
                            <input type="text" name="color" value="{{$car->color}}">
                            <label class="alert" id="color"></label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        رقم اللوحة
                    </th>
                    <td>
                        <div class="col-xs-12">
                            <input type="text" name="plate_number" value="{{$car->plate_number}}">
                            <label class="alert" id="plate_number"></label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
رقم الموتور
                    </th>
                    <td>
                        <div class="col-xs-12">
                            <input type="text" name="motor_number" value="{{$car->motor_number}}">
                            <label class="alert" id="motor_number"></label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        رقم الشاسيه
                    </th>
                    <td>
                        <div class="col-xs-12">
                            <input type="text" name="chassis_number" value="{{ $car->chassis_number}}">
                            <label class="alert" id="chassis_number"></label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        رقم الرخصة
                    </th>
                    <td>
                        <input type="text" name="license_number" value="{{ $car->license_number}}">
                        <label class="alert" id="license_number"></label>

                    </td>
                </tr>
                 <tr>
                    <th>
                 السعر في اليوم
                    </th>
                    <td>
                        <input type="text" name="price" value="{{ $car->price }}">
                        <label class="alert" id="price"></label>

                    </td>
                </tr>
            </table>
            <div class="col-xs-12 text-left" style="margin-top:20px">
                <button type="submit" class="main-btn sm-btn">تعديل</button>
            </div>
        </form>
    </div>
    <div class="reservations box main-box">
        <h3 class="title">الحجوزات</h3>

        @if(sizeof($rentings))
        <table>
            <tr>
                <th>
                    رقم الحجز
                </th>
                <th>
                    اسم العميل
                </th>
                <th>
                    من
                </th>
                <th>
                    الي
                </th>
                <th>
                    المبلغ المطلوب
                </th>
                <th>
                    المبلغ المدفوع
                </th>
                <th>
                    المبلغ المتبقي
                </th>
            </tr>
            @foreach($rentings as $renting)
            <tr>
                <td>
                    {{$renting->id}}
                </td>
                <td>
                    {{$renting->user->display_name}}
                </td>
                <td>
                    {{$renting->start_duration}}
                </td>
                <td>
                    {{$renting->end_duration}}
                </td>
                <td>
                    {{$renting->total}}
                </td>
                <td>
                    {{$renting->payed}}
                </td>
                <td>
                    {{$renting->dept}}
                </td>
            </tr>
                @endforeach
        </table>
        @else
            <h3 class="text-center text-red">لم يتم العثور علي اي حجوزات</h3>
        @endif
    </div>
    <div class="expenses box main-box">
        <h3 class="title">المصاريف</h3>
        <button data-id="{{$car->id}}" data-popup="AddExpense-Popup" id="AddCarExpense" class="main-btn">اضافة مصروف جديد</button>

    @if(sizeof($car_expenses))
            <table>
                <tr>
                    @foreach($expenses_fields as $field)
                        <th> {{ $field }} </th>
                    @endforeach
                    <th>الخيارات</th>
                </tr>
                @foreach($car_expenses as $car_expense)
                    <tr>
                        <td id="title">
                            {{$car_expense->title}}
                        </td>
                        <td id="value">
                            <div class="col-xs-12">
                                {{$car_expense->value}}
                            </div>
                        </td>
                        <td>
                            <button class="main-btn sm-btn" id="EditExpense-btn" data-popup="ExpensesInfo-Popup">
                                <i class="fa fa-pencil"></i>
                            </button>
                            <button class="main-btn sm-btn" data-popup="DeleteExpense-Popup"
                                    data-id="{{$car_expense->id}}">
                                <i class="fa fa-remove"></i>
                            </button>
                        </td>
                    </tr>
                @endforeach
            </table>
        @else
            <h3 class="text-red text-center">لا توجد اي مصاريف بعد </h3>
        @endif
    </div>
    <div class="attachments box main-box">
        <h3 class="title">الملفات المرفقة</h3>
        <div class="col-xs-12 text-right" style="margin:5px 0">
            <button type="button" class="main-btn" data-popup="AddAttachment-Popup">اضافة مرفق جديد</button>
        </div>
        <table border="1">
            @if(sizeof($car->attachments))
            @foreach($car->attachments as $attachment)
            <tr>
                <th>
                   {{$attachment->title}}
                </th>
                <td>
                    <img src="{{$attachment->value}}" width="100" height="100">
                    <a style="margin-top:5px;display:block" href="{{$attachment->value}}" download><button class="main-btn sm-btn">تحميل</button></a>

                </td>
            </tr>
                @endforeach
            @else
                <h3 class="text-red text-center">لا توجد اي مرفقات بعد </h3>
                <div class="clearfix"></div>
            @endif
        </table>

    </div>
@endsection
@section('script')
    <script>
        $("#car_image").fileinput({
            showUpload: false,
            showCaption: false,
            browseClass: "btn main-btn",
            fileType: "any",
            previewFileIcon: "<i class='glyphicon glyphicon-king'></i>"
        });
    </script>
    <script src="{{ asset('AjaxRequests/CarProfile.js') }}"></script>
    <script src="{{ asset('AjaxRequests/Expenses.js') }}"></script>
    <script src="{{ asset('AjaxRequests/CarExpenses.js') }}"></script>


@endsection

resources/views/pages/cars.blade.php
@extends('layouts.dashboard')

@section('contents')
    <div id="DeleteCar-Popup" class="popup">
        <i class="fa fa-close text-danger" data-toggle="tooltip" data-placement="left" title="اغلاق"></i>
        <!--===== POPUP TITLE -=====-->
        <div class="popup-title">
            <h2>حذف المستخدم</h2>
            <br>
            <hr>
            <hr>
        </div>
        <!--===== POPUP BODY ======-->
        <div class="popup-body text-center">
            <form id="DeleteCar" type="POST">
                <h3 class="text-red "> هل انت متأكد بأنك تريد حذف هذه السيارة؟</h3>
                {!! csrf_field() !!}

                <input type="text" class="" name="id" id="IDVal">
                <div class="text-center">
                    <button type="submit" class="main-btn">نعم</button>
                </div>
                <div class="alert"role="alert">

                </div>
            </form>
        </div>
    </div>
    <!-- START ADD CAR FORM -->
    <div id="AddCar-Popup" class="popup">
        <i class="fa fa-close text-danger" data-toggle="tooltip" data-placement="left" title="اغلاق"></i>
        <!--===== POPUP TITLE -=====-->
        <div class="popup-title">
            <h2>اضافة سيارة جديد</h2>
            <br>
            <hr>
            <hr>
        </div>
        <!--===== POPUP BODY ======-->
        <div class="popup-body">
            <form id="car_register" enctype="multipart/form-data">
                {!! csrf_field() !!}
                @foreach($cars_register_fields as $register_field)
                    @if($register_field['type'] == 'select')
                        <div class="col-md-6 col-xs-12 ">
                            <select name="{{ $register_field['name'] }}">
                                <option value="">{{ $register_field['placeholder'] }}</option>
                                @foreach($register_field['options'] as $option)
                                    <option value="{{ $option['value'] }}">{{ $option['display_name'] }}</option>
                                @endforeach
                            </select>
                            <label id="{{ "cars_".$register_field['name'] }}"></label>
                        </div>
                    @else
                        <div class="col-md-6 col-xs-12 ">
                            <input type="{{ $register_field['type'] }}" name="{{ $register_field['name'] }}"
                                   placeholder="{{ $register_field['placeholder'] }}">
                            <label id="{{ "cars_".$register_field['name'] }}"></label>
                        </div>
                    @endif
                @endforeach

                <div class="col-xs-6">
                    <h5 class="fl-right" style="margin:0;margin-left:30px;margin-top:12px;font-size:18px">الصورة الرئيسية</h5>
                    <input type="file" name="picture" id="car_image">
                </div>
                <div class="clearfix">
                </div>
                <br>
                <div class="text-center">
                    <button type="submit" class="main-btn">اضافة سيارة</button>
                </div>
            </form>
        </div>
    </div>
    <!-- END ADD CAR FORM -->



    <div role="tabpanel" class="tab-pane fade in active" id="Cars">
        <button data-popup="AddCar-Popup" class="main-btn col-xs-3">اضافة سيارة</button>
        <form class="col-xs-9">
            <div class="col-md-10 col-xs-9" id="Cars-Filter">

            </div>
            <div class="col-md-2 col-xs-3" id="Cars-Length">

            </div>
        </form>
        <div class="clearfix"></div>
        <div class="cars box main-box">
            <table id="Cars-table" class="list-view">
                <thead>
                <tr>
                    @foreach($cars_fields as $field)
                        <th>{{ $field }}</th>
                    @endforeach
                    <th>الخيارات</th>
                </tr>
                </thead>
                <tbody>


                @foreach($cars as $car)
                    <tr>
                        <td>
                            <img src="{{ $car->picture }}" alt="لا يوجد صورة" >
                        </td>
                        <td>
                            {{ $car->type }}
                        </td>
                        <td>
                            {{ $car->model }}
                        </td>
                        <td>
                            {{ $car->color }}
                        </td>
                        <td>
                            {{ $car->plate_number }}
                        </td>
                        <td>
                            {{ $car->motor_number }}
                        </td>
                        <td>
                            {{ $car->chassis_number }}
                        </td>
                        <td>
                            {{ $car->license_number }}
                        </td>
                        <td>
                            {{ $car->first_name." ".$car->last_name }}
                        </td>
                        <td>
                            في اليوم{{ $car->price }}
                        </td>
                        <td>
                            <button class="main-btn sm-btn" data-popup="DeleteCar-Popup" data-id="{{$car->id}}"><i class="fa fa-remove"></i></button>
                            <a href="{{"/car/"."-".$car->id}}"><button class="main-btn sm-btn">التفاصيل</button></a>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>

@endsection
@section('script')
    <script src="{{ asset('AjaxRequests/RegisterCar.js') }}"></script>
    <script src="{{ asset('AjaxRequests/DeleteCar.js') }}"></script>
    <script>
        $("#Cars-table_filter input").attr("placeholder","بحث عن سيارة ؟");
    </script>
@endsection

resources/views/pages/expenses.blade.php
@extends('layouts.dashboard')

@section('contents')
    @include('layouts.Expenses_Forms')
    <div role="tabpanel" class="tab-pane fade in active" id="Expenses">
        <section id="General" class="general">
            <button data-popup="AddExpense-Popup" id="AddExpense" class="main-btn">اضافة مصروف جديد</button>
            <div class="expenses box main-box">
                @if(sizeof($general_expenses))
            <table>
                <tr>
                    @foreach($expenses_fields as $field)
                        <th> {{ $field }} </th>
                    @endforeach
                    <th>الخيارات</th>
                </tr>
                @foreach($general_expenses as $general_expense)
                <tr>
                    <td id="title">
                        {{$general_expense->title}}
                    </td>
                    <td id="value">
                        <div class="col-xs-12">
                            {{$general_expense->value}}
                        </div>
                    </td>
                    <td>
                        <button class="main-btn sm-btn" id="EditExpense-btn" data-popup="ExpensesInfo-Popup">
                            <i class="fa fa-pencil"></i>
                        </button>
                        <button class="main-btn sm-btn" data-popup="DeleteExpense-Popup"
                                data-id="{{$general_expense->id}}">
                            <i class="fa fa-remove"></i>
                        </button>
                    </td>
                </tr>
                @endforeach
            </table>
                    @else
                <h3 class="text-red text-center">لا توجد اي مصاريف بعد </h3>
                    @endif
            </div>
            </section>

    </div>

@endsection
@section('script')
    <script src="{{ asset('AjaxRequests/Expenses.js') }}"></script>
    <script src="{{ asset('AjaxRequests/GeneralExpenses.js') }}"></script>
@endsection

resources/views/pages/recive.blade.php
@extends('layouts.dashboard')

@section('contents')
    <div id="ReciveCar-Popup" class="popup">
        <i class="fa fa-close text-danger" data-toggle="tooltip" data-placement="left" title="اغلاق"></i>
        <!--===== POPUP TITLE -=====-->
        <div class="popup-title">
            <h2>استلام السيارة</h2>
            <br>
            <hr>
            <hr>
        </div>
        <!--===== POPUP BODY ======-->
        <div class="popup-body text-center">
            <form id="" type="POST" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <input class="hidden" name="id" id="IDVal">
                <input class="hidden" name="plate_number" value="123" id="">
                <div class="col-xs-12">
                    <input type="text" name="KMCounter" placeholder="عداد الكيلومترات">
                    <label for="" id="KMCounter"></label>
                </div>
                <div class="col-xs-12 text-right">
                    <h5 style="float:right;margin:10px 20px;font-size:16px">اضافة صورة</h5>
                    <input type="file" name="picture" id="car_image">
                </div>
                <div class="col-xs-12">
                    <textarea type="text" name="notes" rows="5" placeholder="ملاحظات"></textarea> {{-- make it optional --}}

                </div>
                <div class="col-xs-6">
                    <input type="number" name="userate" placeholder="تقييم الاستهلاك (/10)">
                    <label for="" id="userate"></label>
                </div>
                <div class="col-xs-6">
                    <input type="number" name="payrate" placeholder="تقييم الاستهلاك (/10)">
                    <label for="" id="payrate"></label>
                </div>
                <div class="text-center">
                    <button type="submit" class="main-btn">استلام</button>
                </div>
                <div class="alert">

                </div>
            </form>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane fade in active" id="Recive">
        <section class="reservations col-xs-12">
            @foreach($rentings as $renting)
                @if($renting->deleted_at==NULL)
            <div class=" item col-md-3" data-popup="ReciveCar-Popup" data-id="{{$renting->id}}">
                <div class="image">
                    <img src="{{$renting->car->picture}}">
                </div>
                <div class="text text-center">
               <h4 class="text-red">{{$renting->car->type}}</h4>
                    <h5>{{$renting->user->display_name}}</h5>
                    <h6>{{date_format( new DateTime($renting->end_duration),"Y-m-d")}}</h6>
                </div>
            </div>
                @endif
            @endforeach
        </section>
    </div>
@endsection
@section('script')
    <script src="{{ asset('AjaxRequests/ReciveCar.js') }}"></script>
@endsection

resources/views/pages/reservation.blade.php
@extends('layouts.dashboard')

@section('contents')
    <div id="DeleteReservation-Popup" class="popup">
        <i class="fa fa-close text-danger" data-toggle="tooltip" data-placement="left" title="اغلاق"></i>
        <!--===== POPUP TITLE -=====-->
        <div class="popup-title">
            <h2>حذف الحجز</h2>
            <br>
            <hr>
            <hr>
        </div>
        <!--===== POPUP BODY ======-->
        <div class="popup-body text-center">
            <form id="DeleteReservation" type="POST">
                <h3 class="text-red "> هل انت متأكد بأنك تريد حذف هذا الحجز؟</h3>
                {!! csrf_field() !!}

                <input type="text" class="hidden" name="id" id="IDVal">
                <div class="text-center">
                    <button type="submit" class="main-btn">نعم</button>
                </div>
                <div class="alert"role="alert">

                </div>
            </form>
        </div>
    </div>
    <!-- START ADD Reservation FORM -->
    <div id="AddReservation-Popup" class="popup">
        <i class="fa fa-close text-danger" data-toggle="tooltip" data-placement="left" title="اغلاق"></i>
        <!--===== POPUP TITLE -=====-->
        <div class="popup-title">
            <h2>اضافة حجز جديد</h2>
            <br>
            <hr>
            <hr>
        </div>
        <!--===== POPUP BODY ======-->
        <div class="popup-body">
            @include('layouts/reservation_form')
        </div>
    </div>
    <!-- END ADD Reservation FORM -->

<div role="tabpanel" class="tab-pane fade in active" id="Reservations">
    <button data-popup="AddReservation-Popup" class="main-btn col-xs-3">اضافة حجز</button>
    <form class="col-xs-9">
        <div class="col-md-10 col-xs-9" id="Reservations-Filter">

        </div>
        <div class="col-md-2 col-xs-3" id="Reservations-Length">

        </div>
    </form>
    <div class="clearfix"></div>
    <div class="reservations box main-box">
        <table id="Reservations-table" class="list-view">
            <thead>
            <tr>
                @foreach($rentings_fields as $field)
                    <th>{{ $field }}</th>
                @endforeach
                <th>الحالة</th>
                <th>الخيارات</th>
            </tr>
            </thead>
            <tbody>


            @foreach($rentings as $renting)
                <tr>
                    <td>
                        {{$renting->id}}
                    </td>
                    <td>
                        @if($renting->user)
                            {{ $renting->user->display_name }}
                            @else
                            العميل محذوف
                            @endif


                    </td>
                    <td>
                        @if($renting->car)
                        {{$renting->car->type}}
                            @else
    السيارة محذوفة
                            @endif
                    </td>
                    <td>
                        {{ date_format( new DateTime($renting->start_duration),"Y-m-d")}}
                    </td>
                    <td>
                        {{ date_format( new DateTime($renting->end_duration),"Y-m-d")}}
                    </td>
                    <td>
                        {{$renting->total}}
                    </td>
                    <td>
                        {{$renting->payed}}
                    </td>
                    <td>
                        {{$renting->dept}}
                    </td>
                    <td>
                        @if($renting->deleted_at == NULL)
                            <span style="padding:5px;" class="btn-primary btn-sm">جديد</span>
                        @else
                            <span style="padding:5px;" class="btn-danger btn-sm">منتهي</span>
                            @endif
                    </td>

                    <td>
                        @if($renting->deleted_at == NULL)
                        {{--<button class="main-btn sm-btn" id="EditReservation-btn" data-popup="EditReservation-Popup" data-id="{{ $renting->id }}"><i class="fa fa-pencil"></i></button>--}}
                        <button class="main-btn sm-btn" id="DeleteReservation-btn" data-popup="DeleteReservation-Popup" data-id="{{ $renting->id }}"><i class="fa fa-remove"></i></button>
                        @endif
                    </td>

                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
</div>

@endsection
@section('script')
    <script src="{{ asset('AjaxRequests/RegisterReservation.js') }}"></script>
    <script src="{{ asset('AjaxRequests/DeleteReservation.js') }}"></script>
    <script>
        $("#Reservations-table_filter input").attr("placeholder","بحث عن حجز ؟");
    </script>
@endsection